# Generated by Django 4.1.4 on 2022-12-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_family_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.student'),
            preserve_default=False,
        ),
    ]
