# Generated by Django 4.1.4 on 2022-12-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_family_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['id'], 'verbose_name': 'Family'},
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('father_name', 'brother')},
        ),
    ]
